//
// Created by Alex on 18/09/2018.
//

#ifndef FINTEGRALPROJECT_RISKNEUTRALLOGNORMPRICE_H
#define FINTEGRALPROJECT_RISKNEUTRALLOGNORMPRICE_H


class RiskNeutralLogNormPrice {

};


#endif //FINTEGRALPROJECT_RISKNEUTRALLOGNORMPRICE_H
